apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: react-test-docker
spec:
  encryptedData:
    .dockerconfigjson: AQCI2qTWylHo3CAtCDn/GMkX85BwQJrKLtf6Ve/jmbCSMsfgAbYNPvmfX7d/vr92Fqt+5/SqFfxekv7c0wTwGwV4NtB2tMOc/miAO2E8PbAfQA8q5ZXpif+B66WtHjpY0I2TMWDsWw25o2fcMm5NpaoyNVlU0zZnTevoJvoh+9TJFlj1fXBdMIesKW6X+mcMEEYexfdvAfqqsap71Mvc8U1gCUBABlenhLWZ0VPlQSOMjibI49fD4OL8NIS9S63vfFrAec0Qv745e9gIK+Y9ZFYg9IRDymh9ag0ZhlGSenDnBvUwbIMY3wvOg0ThjOwf/vUDx1fOzgAIJ2nAACKJUR72JyEr5I116hezuHLeamjQiYYf5mOHxyVIpFpVB0mHmUEEF61/lROq+SBvtPutMf+f1zzJ36Zc+jzqWo3BJ0gza6p7yW4JTAGItU6Hdvl2MfKe/BWgfq6LwrrShp8WHrPdwGR+15l40Z87kXCPfWZ2WMktBovTsS6eQ84zp+KR/xe03dc7oWFOsTLU9mm4v1iQetujF2prEfazgj9bdD/jJ2WISkJRrO5IqKPrtW5dxwXzkmOgj9UvLoUKe3a56bkgKaPiXuBe5EGm
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: react-test-docker
    type: kubernetes.io/dockerconfigjson
